### ISSUE TITLE
Button to change units

### ISSUE THREAD

**Issue by Johnnywick1** [anikets349/weather-app#1]
Hello,

Great app, but there is no switch button to change units from metric to imperial. Could you repair it?

Thank you

**Comment by Johnnywick1** [comment]
...and the Humidity should be I think in % .  Is it possible to add Wind speed and direction? Coul you add below main temperature icon instead of inscription? 

Thank you

**Comment by anikets349** [comment]
Thanks for your comments!

Sure, I'll try to implement the changes you suggested.

**Comment by anikets349** [comment]
Added all the functionalities you requested. 
Closing this issue. 
Thanks!
